"""What Prefs ANSWERS, pinned before its shape changes.

Line 9 breaks a 2,062-line class along measured seams. A refactor of
a settings object is only safe if every question it answers keeps its
answer, so this records the answers themselves - every public
property, and a full save/load round trip - rather than the internals
that produce them.

Deliberately not a snapshot file. A committed golden would have to be
regenerated by hand on every genuine preference addition, and a
regenerated golden proves whatever it was regenerated from. This
asserts the two INVARIANTS instead:

  * a round trip through disk changes no answer, and
  * a fresh instance and a loaded-from-its-own-save instance agree.

Both hold before the extraction and must hold after it, and neither
needs updating when a preference is added.
"""

import os
import shutil
import sys
import tempfile
import unittest

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
from PySide6 import QtWidgets  # noqa: E402

_app = QtWidgets.QApplication.instance() or QtWidgets.QApplication([])

sys.path.insert(
    0, os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.abspath(__file__)))))

import hou  # noqa: E402,F401

from amaze.prefs import prefs as prefs_mod  # noqa: E402
from amaze.tests import test_support  # noqa: E402,F401 - redirects the log


#: Answers that are allowed to differ between two instances because
#: they are about THIS machine or THIS moment, not about the settings.
_VOLATILE = {
    "dir", "real_dir",          # a fixture points these at a temp folder
    "path",                     # where the settings file itself lives
    "data",                     # the raw document, compared separately
}


def _answers(p) -> dict:
    """Every public property's value, by name."""
    out = {}
    for name in dir(type(p)):
        if name.startswith("_") or name in _VOLATILE:
            continue
        if not isinstance(getattr(type(p), name, None), property):
            continue
        try:
            value = getattr(p, name)
        except Exception as exc:            # noqa: BLE001
            value = "RAISED %s" % type(exc).__name__
        if isinstance(value, (list, set)):
            value = list(value)
        out[name] = value
    return out


class PrefsCase(unittest.TestCase):

    def _fresh(self):
        folder = tempfile.mkdtemp(prefix="amaze_prefs_eq_")
        self.addCleanup(shutil.rmtree, folder, True)
        p = prefs_mod.Prefs()
        p.path = folder
        p.load()
        return p, folder

    def test_a_property_answers_the_same_after_a_round_trip(self):
        """Save, load the same file back, and every answer holds."""
        p, folder = self._fresh()
        before = _answers(p)
        self.assertTrue(before, "no properties were read at all")

        p.save()
        again = prefs_mod.Prefs()
        again.path = folder
        again.load()

        after = _answers(again)
        differing = {k: (before[k], after[k])
                     for k in before if before[k] != after.get(k)}
        self.assertEqual(
            {}, differing,
            "a round trip through disk changed what Prefs answers")

    def test_every_property_is_readable(self):
        """A property that raises is a broken answer whatever its
        value would have been - and an extraction is exactly where one
        starts reading an attribute that moved."""
        p, _folder = self._fresh()
        raised = {k: v for k, v in _answers(p).items()
                  if isinstance(v, str) and v.startswith("RAISED ")}
        self.assertEqual({}, raised, "a property raised when read")

    def test_the_written_document_reaches_a_fixed_point(self):
        """The raw document too, not only the accessors: a key that
        stops being written is invisible to the property test as long
        as its default matches.

        A FIXED POINT, not first-equals-second. One-time migrations
        are allowed to happen once, and this test found a real one on
        its first run: `load()` marks a newly introduced section as
        seen, and a folder with no settings file yet short-circuits
        before reaching that - so save #1 legitimately lacks a key
        that save #2 carries. What must never drift is the round trip
        AFTER everything one-time has run.
        """
        import json

        p, folder = self._fresh()
        settings = os.path.join(folder, "settings.json")

        def save_load_read():
            live = prefs_mod.Prefs()
            live.path = folder
            live.load()
            live.save()
            with open(settings, encoding="utf-8-sig") as handle:
                return json.load(handle)

        p.save()                    # the file has to exist to be loaded
        settled = save_load_read()  # every one-time step has now run
        again = save_load_read()

        self.assertEqual(
            sorted(settled), sorted(again),
            "the set of keys written is still changing after the "
            "one-time steps have run")
        self.assertEqual(settled, again,
                         "a value changed across a settled round trip")


if __name__ == "__main__":
    unittest.main()
